<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>ERA.Framework.Storage</RootNamespace>
		<AssemblyName>ERA.Framework.Storage</AssemblyName>
		<PackageId>ERA.Framework.Storage</PackageId>
		<NoWarn>$(NoWarn);CA1031;CA1056;CA1002;CA2227;CA1812;CA1308;CA1062</NoWarn>
		<Version>10.0.0</Version>
		<Authors>Mahmudur Rahman</Authors>
		<Company>ERA Info Tech</Company>
		<Description>A production-ready modular .NET framework for building enterprise applications</Description>
		<PackageProjectUrl />
		<RepositoryUrl />
		<PackageTags>Modular;CQRS;VerticalSlice;DotNet;CleanArchitecture</PackageTags>
	</PropertyGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Core\Core.csproj" />
		<ProjectReference Include="..\Shared\Shared.csproj" />
	</ItemGroup>
	
	<ItemGroup>
	  <Folder Include="AWS\" />
	</ItemGroup>
	
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="AWSSDK.S3" />
	</ItemGroup>
	
</Project>
