// <auto-generated />
using System;
using FSH.Modules.Auditing.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace FSH.Playground.Migrations.Oracle.Audit
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260210075841_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FSH.Modules.Auditing.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("EventType")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("RequestId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<byte>("Severity")
                        .HasColumnType("NUMBER(3)");

                    b.Property<string>("Source")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SpanId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long>("Tags")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("TenantId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("TraceId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("TenantId");

                    b.ToTable("AuditRecords", (string)null);

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });
#pragma warning restore 612, 618
        }
    }
}
